# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d7d41d749a0035b5ff211bafcb966ff8bbf6d607c4892707c1bfc68e038eea66d8a6d2f1f5c344f7d0e032d6aea910582198e71a9f503b3f76478435663c947

test:
  secret_key_base: 704b2d8e9987d994dc86f46008593317ba2f4abd968519f7030a6cb28f365e7c9e080ad7678e1377f0d3271cda0628620214a3030318673913640920e3501837

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
